services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - my_network_fart

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - fart_mysql
    env_file:
      - ./server/.env
    networks:
      - my_network_fart

  fart_mysql:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    container_name: fart_mysql
    image: fart_mysql_image
    ports:
      - "${MYSQLDB_LOCAL_PORT:-3307}:${MYSQLDB_DOCKER_PORT:-3306}"
    env_file:
      - ./database/.env
    volumes:
      - ./database/fart_db.sql:/docker-entrypoint-initdb.d/fart_db.sql
    networks:
      - my_network_fart

networks:
  my_network_fart:
    driver: bridge

